services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=orca-mini:3b-q4_1
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama/models
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 60s
      timeout: 20s
      retries: 5

networks:
  app-network:
    driver: bridge
